### ISSUE TITLE
Move to main?

### ISSUE THREAD

**Issue by zklaus** [conda-forge/exceptiongroup-feedstock#7]
### Comment:

Is there a particular reason to keep this one away from `main`?

**Comment by xylar** [comment]
Yep, there still hasn't been a release yet.

**Comment by zklaus** [comment]
Ah, yes, got you. I have a project that pulls it in from pypi instead, but that's something to be addressed upstream. Thanks for your quick response, @xylar !

**Comment by xylar** [comment]
@zklaus, do you need any help using the dev label in the meantime or have you got it?

**Comment by zklaus** [comment]
I think I got it. Thanks for offering, will come back to you if needed. :grin:

**Comment by xylar** [comment]
I'm moving to main in #8.  Sorry, I didn't know that this was allowed until today.
